model:
  path: 'D:\namespace\tensorflow-project-namespace\MCP-Win-Control\model\qwen3-0.6'
  name: 'default-model'

chroma:
  save_path: 'D:\namespace\tensorflow-project-namespace\MCP-Win-Control\dataset\chroma'

sqlite:
  db_path: 'D:\namespace\tensorflow-project-namespace\MCP-Win-Control\dataset\sqlite\sqlite.db'